"""Storage layer — SQLite by default, Postgres (Supabase) when DATABASE_URL is set.

Signals are immutable — inserts only, never updates.

Design: rather than rewriting every query for Postgres, Postgres is taught the
SQLite dialect the codebase uses (db/pg_compat.sql: julianday, datetime, date,
group_concat), and the driver translates only placeholders (? -> %s). One set
of queries, two backends, and the tested SQLite behaviour stays authoritative.

Env:
  DATABASE_URL / SUPABASE_DB_URL   postgres://... turns on the Postgres backend
  DEAL_ENGINE_DB                   override the SQLite file path (tests use this)
"""
from __future__ import annotations
import json
import logging
import os
import re
import sqlite3
import threading
from datetime import datetime, timedelta, timezone
from pathlib import Path

from .config import DB_PATH, ROOT

DATABASE_URL = os.environ.get("DATABASE_URL") or os.environ.get("SUPABASE_DB_URL") or ""
BACKEND = "postgres" if DATABASE_URL.startswith(("postgres://", "postgresql://")) else "sqlite"

_conn = None
_lock = threading.Lock()          # psycopg connections are not thread-safe
_PG_ERROR = ""                    # why Postgres was refused, if it was


def _diagnose_url(url: str) -> str:
    """Plain-English reason a Supabase URL will not work, checked before dialling.
    Returns '' when the string looks usable."""
    if "[YOUR-PASSWORD]" in url or "[your-password]" in url.lower():
        return ("the connection string still contains the literal [YOUR-PASSWORD] "
                "placeholder — replace it (brackets included) with your database password")
    host = re.sub(r"^.*@", "", url).split("/")[0]
    if re.match(r"^db\.[a-z0-9]+\.supabase\.co", host):
        return ("this is Supabase's Direct connection string, which is IPv6-only and "
                "unreachable from most hosts — use the Transaction pooler string instead "
                "(Connect → Transaction pooler, host ends in .pooler.supabase.com)")
    after = url.split("://", 1)[-1]
    if after.count("@") > 1:
        return ("the password contains an unencoded '@', so the address is parsed at the "
                "wrong point — percent-encode it as %40, or reset the database password "
                "to letters and digits only")
    if "@" in after and ":" in after.rsplit("@", 1)[0]:
        pwd = after.rsplit("@", 1)[0].split(":", 1)[1]
        if any(c in pwd for c in "/?#[] "):
            return ("the password contains a character that breaks the address (/ ? # [ ] "
                    "or a space) — percent-encode it, or reset the database password to "
                    "letters and digits only")
    return ""


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---- display timezone ------------------------------------------------------
# Everything is STORED in UTC — that is not negotiable, because a database that
# mixes local times cannot be compared, sorted or migrated safely. Only the
# rendering is localised. A fixed offset (not zoneinfo) keeps this correct on
# slim containers with no tzdata, and India has no daylight saving to track.
DISPLAY_TZ_LABEL = os.environ.get("DISPLAY_TZ_LABEL", "IST")
DISPLAY_TZ_OFFSET_MIN = int(os.environ.get("DISPLAY_TZ_OFFSET_MIN", "330"))   # UTC+5:30


def display_tz() -> dict:
    return {"label": DISPLAY_TZ_LABEL, "offset_minutes": DISPLAY_TZ_OFFSET_MIN}


def to_display(iso: str | None, fmt: str = "%Y-%m-%d %H:%M", with_label: bool = True) -> str:
    """UTC ISO string -> local display string. Returns '—' for missing input and
    the original string if it cannot be parsed, so a rendering helper can never
    be the thing that breaks a page."""
    if not iso:
        return "—"
    try:
        dt = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
    except ValueError:
        return str(iso)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    local = dt.astimezone(timezone(timedelta(minutes=DISPLAY_TZ_OFFSET_MIN)))
    return local.strftime(fmt) + (f" {DISPLAY_TZ_LABEL}" if with_label else "")


# ---------------------------------------------------------------- schema ----

def _postgres_schema() -> str:
    """Derive the Postgres DDL from schema.sql — one source of truth, no drift.
    (db/schema.postgres.sql is a checked-in copy of this output, for reading.)"""
    s = (ROOT / "db" / "schema.sql").read_text()
    s = re.sub(r"^PRAGMA.*?$", "", s, flags=re.M)
    s = s.replace("id INTEGER PRIMARY KEY",
                  "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    s = s.replace("DEFAULT (datetime('now'))", "DEFAULT datetime('now')")
    # SQLite resolves forward table references lazily; Postgres would demand a
    # topological creation order. FKs here are documentation — integrity is
    # enforced by the ingest paths — so they are dropped from the PG DDL.
    s = re.sub(r"\s+REFERENCES\s+\w+\(\w+\)", "", s)
    return s


MIGRATIONS: list[tuple[str, str, str]] = [
    ("digests", "delivered", "INTEGER NOT NULL DEFAULT 0"),
    ("digests", "delivery_detail", "TEXT"),
    ("alerts_log", "delivered", "INTEGER NOT NULL DEFAULT 0"),
    ("alerts_log", "delivery_detail", "TEXT"),
    ("sectors_emerging", "companies_json", "TEXT"),
    ("sectors_emerging", "talent_flow", "INTEGER NOT NULL DEFAULT 0"),
    ("sectors_emerging", "terms_json", "TEXT"),
]


def _columns(table: str) -> set[str]:
    if BACKEND == "postgres":
        rows = q("""SELECT column_name FROM information_schema.columns
                    WHERE table_schema='public' AND table_name=?""", (table,))
        return {r["column_name"] for r in rows}
    return {r["name"] for r in _conn.execute(f"PRAGMA table_info({table})")}


def _migrate() -> None:
    for table, column, decl in MIGRATIONS:
        cols = _columns(table)
        if cols and column not in cols:
            _raw_execute(f"ALTER TABLE {table} ADD COLUMN {column} {decl}")


# --------------------------------------------------------------- connect ----

def connect(db_path: Path | None = None):
    """Open the backend. A broken DATABASE_URL must never take the service down:
    Postgres failures fall back to SQLite and are reported loudly through
    backend_info() -> the dashboard banner, never silently swallowed."""
    global _conn, BACKEND, _PG_ERROR
    if _conn is not None:
        return _conn
    if BACKEND == "postgres":
        _PG_ERROR = _diagnose_url(DATABASE_URL)
        if not _PG_ERROR:
            try:
                import psycopg
                from psycopg.rows import dict_row
                _conn = psycopg.connect(DATABASE_URL, autocommit=True,
                                        row_factory=dict_row, connect_timeout=15)
                # Supabase's transaction pooler (PgBouncer in transaction mode) hands
                # each statement a different server connection, so a server-side
                # PREPARE from one statement collides with the next:
                #   DuplicatePreparedStatement: prepared statement "_pg3_0" already exists
                # psycopg3 prepares automatically after 5 identical executions, which is
                # exactly what _migrate() does. None disables that entirely — the correct
                # setting for any pooled connection, and harmless on a direct one.
                _conn.prepare_threshold = None
                with _lock:
                    _conn.execute((ROOT / "db" / "pg_compat.sql").read_text())
                    _conn.execute(_postgres_schema())
                _migrate()          # inside the guard: a migration failure must also
                                    # degrade to SQLite rather than kill the service
            except Exception as e:  # noqa: BLE001 — any failure means "no Postgres"
                try:
                    if _conn is not None:
                        _conn.close()
                except Exception:  # noqa: BLE001
                    pass
                _conn = None
                _PG_ERROR = f"{type(e).__name__}: {str(e).strip()[:300]}"
        if _PG_ERROR:
            BACKEND = "sqlite"
            logging.getLogger("dealengine").error(
                "DATABASE_URL set but unusable — falling back to the local SQLite file "
                "(data will NOT survive restarts). Reason: %s", _PG_ERROR)
    if BACKEND == "sqlite":
        path = db_path or DB_PATH
        path.parent.mkdir(parents=True, exist_ok=True)
        _conn = sqlite3.connect(path, check_same_thread=False)
        _conn.row_factory = sqlite3.Row
        _conn.executescript((ROOT / "db" / "schema.sql").read_text())
        _conn.commit()
        _migrate()
    return _conn


def _translate(sql: str) -> str:
    """? -> %s for psycopg; literal % (LIKE 'demo_%') must be escaped as %%
    because psycopg treats % as a placeholder marker when params are given."""
    if BACKEND != "postgres":
        return sql
    return sql.replace("%", "%%").replace("?", "%s")


_DROPPED = ("the connection is closed", "connection is bad", "server closed",
            "connection already closed", "consuming input failed", "ssl connection has been closed")


def _is_dropped_connection(exc: Exception) -> bool:
    """A pooled Supabase connection can be recycled out from under a long-running
    service. That must cost one reconnect, not a dead dashboard."""
    return BACKEND == "postgres" and any(s in str(exc).lower() for s in _DROPPED)


def _reconnect() -> None:
    global _conn
    logging.getLogger("dealengine").warning("database connection dropped — reconnecting")
    try:
        if _conn is not None:
            _conn.close()
    except Exception:  # noqa: BLE001
        pass
    _conn = None
    connect()


def _pg_exec(sql: str, params: tuple, fetch: bool):
    """Run one Postgres statement, reconnecting once if the pool dropped us."""
    for attempt in (0, 1):
        try:
            with _lock:
                cur = _conn.execute(_translate(sql), params) if params else _conn.execute(sql)
                return cur.fetchall() if fetch else cur
        except Exception as exc:  # noqa: BLE001
            if attempt == 0 and _is_dropped_connection(exc):
                _reconnect()
                continue
            raise


def _raw_execute(sql: str, params: tuple = ()):
    if BACKEND == "postgres":
        return _pg_exec(sql, params, fetch=False)
    cur = _conn.execute(sql, params)
    _conn.commit()
    return cur


# ---------------------------------------------------------------- queries ----

def q(sql: str, params: tuple = ()) -> list:
    connect()
    if BACKEND == "postgres":
        return _pg_exec(sql, params, fetch=True)
    return _conn.execute(sql, params).fetchall()


def q1(sql: str, params: tuple = ()):
    rows = q(sql, params)
    return rows[0] if rows else None


def execute(sql: str, params: tuple = ()) -> int:
    connect()
    cur = _raw_execute(sql, params)
    if BACKEND == "postgres":
        return cur.rowcount
    return cur.lastrowid


def insert(table: str, values: dict) -> int:
    connect()
    keys = ", ".join(values)
    ph = ", ".join("?" for _ in values)
    sql = f"INSERT INTO {table} ({keys}) VALUES ({ph})"
    if BACKEND == "postgres":
        cur = _pg_exec(sql + " RETURNING id", tuple(values.values()), fetch=False)
        return cur.fetchone()["id"]
    cur = _conn.execute(sql, tuple(values.values()))
    _conn.commit()
    return cur.lastrowid


def _is_unique_violation(exc: Exception) -> bool:
    if isinstance(exc, sqlite3.IntegrityError):
        return True
    try:
        from psycopg import errors as pg_errors
        return isinstance(exc, pg_errors.UniqueViolation)
    except ImportError:
        return False


def insert_signal(source_id: int, kind: str, observed_at: str, payload: dict,
                  url: str | None, dedupe_key: str, raw: str | None = None,
                  company_id: int | None = None, fetch_mode: str = "live") -> int | None:
    """Idempotent immutable insert. Returns id, or None if already ingested."""
    connect()
    try:
        return insert("signals", {
            "source_id": source_id, "company_id": company_id, "kind": kind,
            "observed_at": observed_at, "fetched_at": now_iso(),
            "fetch_mode": fetch_mode, "payload_json": json.dumps(payload, default=str),
            "raw": raw, "url": url, "dedupe_key": dedupe_key})
    except Exception as exc:  # noqa: BLE001
        if _is_unique_violation(exc):
            return None  # duplicate dedupe_key — already ingested
        raise


def get_source_id(name: str) -> int:
    row = q1("SELECT id FROM sources WHERE name = ?", (name,))
    if row:
        return row["id"]
    return insert("sources", {"name": name, "adapter": name, "interval_minutes": 60})


def checkpoint_get(source_name: str) -> str | None:
    row = q1("SELECT checkpoint FROM checkpoints WHERE source_name = ?", (source_name,))
    return row["checkpoint"] if row else None


def checkpoint_set(source_name: str, value: str) -> None:
    execute("INSERT INTO checkpoints (source_name, checkpoint, updated_at) VALUES (?,?,?) "
            "ON CONFLICT(source_name) DO UPDATE SET checkpoint=excluded.checkpoint,"
            " updated_at=excluded.updated_at", (source_name, value, now_iso()))


def backend_info() -> dict:
    """Honest storage posture for the dashboard/status surfaces."""
    if BACKEND == "postgres":
        host = re.sub(r"^.*@", "", DATABASE_URL).split("/")[0]
        return {"backend": "postgres", "durable": True, "host": host,
                "note": "data survives restarts and redeploys"}
    if _PG_ERROR:
        return {"backend": "sqlite", "durable": False, "path": str(DB_PATH),
                "error": _PG_ERROR,
                "note": "a database address was configured but could not be used, so the "
                        "engine is running on a temporary local file — searches and history "
                        "will be lost when the service restarts. See SUPABASE.md."}
    return {"backend": "sqlite", "durable": False, "path": str(DB_PATH),
            "note": "local file — on ephemeral hosting this is wiped by restarts;"
                    " set DATABASE_URL (Supabase) for durability"}
