-- AUTO-DERIVED from schema.sql (see engine/db.py). Requires pg_compat.sql.
-- Deal Sourcing & Discovery Engine — SQLite schema
-- Signals are immutable: never UPDATE a signals row. Company state is derived.




CREATE TABLE IF NOT EXISTS sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  adapter TEXT NOT NULL,
  interval_minutes INTEGER NOT NULL DEFAULT 60,
  requires_license INTEGER NOT NULL DEFAULT 0,
  license_vendor TEXT,
  last_ok_at TEXT,
  last_attempt_at TEXT,
  health TEXT NOT NULL DEFAULT 'unknown',   -- ok | degraded | license_required | down | unknown
  error_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT
);

CREATE TABLE IF NOT EXISTS signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id INTEGER NOT NULL,
  company_id INTEGER,
  kind TEXT NOT NULL,            -- funding_event | filing | launch | news | research | repo | commentary | hiring | fund_formation
  observed_at TEXT NOT NULL,     -- when the underlying event was observed/published (ISO)
  fetched_at TEXT NOT NULL,      -- when we fetched it
  fetch_mode TEXT NOT NULL DEFAULT 'live',  -- live | cached_snapshot
  payload_json TEXT NOT NULL,    -- parsed fields
  raw TEXT,                      -- raw excerpt for provenance
  url TEXT,                      -- real, fetchable source URL
  dedupe_key TEXT UNIQUE         -- source-scoped id to make ingest idempotent
);
CREATE INDEX IF NOT EXISTS idx_signals_company ON signals(company_id);
CREATE INDEX IF NOT EXISTS idx_signals_kind ON signals(kind);
CREATE INDEX IF NOT EXISTS idx_signals_observed ON signals(observed_at);

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT UNIQUE,            -- canonical key when known
  name TEXT NOT NULL,
  description TEXT,
  sector TEXT,
  sub_sector TEXT,
  stage TEXT,                    -- pre-seed | seed | series-a | series-b | growth | unknown
  country TEXT,
  founded_year INTEGER,
  hq TEXT,
  last_signal_at TEXT,
  status TEXT NOT NULL DEFAULT 'candidate',  -- candidate | filtered | pipeline | watchlist | hot | stale_review | removed
  market_rank INTEGER,
  is_synthetic INTEGER NOT NULL DEFAULT 0,   -- demo-only records; NEVER shown in real tabs
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS company_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL,
  alias TEXT NOT NULL,
  alias_type TEXT NOT NULL,      -- name | domain | linkedin | uuid | mention
  merged_from TEXT,              -- JSON snapshot of merged company record (reversibility)
  confidence REAL,
  merged_at TEXT,
  source_signal_id INTEGER
);
CREATE INDEX IF NOT EXISTS idx_alias_alias ON company_aliases(alias);

CREATE TABLE IF NOT EXISTS founders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER,
  name TEXT NOT NULL,
  linkedin_url TEXT,
  prior_companies_json TEXT,
  prior_exits INTEGER,
  frontier_lab_alum INTEGER,
  founder_score REAL,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS funding_rounds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL,
  stage TEXT,
  amount_usd REAL,
  valuation_usd REAL,
  announced_at TEXT,
  lead_investor_id INTEGER,
  source_signal_id INTEGER
);

CREATE TABLE IF NOT EXISTS investors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  tier INTEGER,                  -- 1 | 2 | 3 | NULL unknown
  aum_usd REAL,
  sector_distribution_json TEXT, -- historical distribution, derived from investments
  stated_focus_json TEXT         -- from config; basis for thesis-shift detection
);

CREATE TABLE IF NOT EXISTS investments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investor_id INTEGER NOT NULL,
  company_id INTEGER NOT NULL,
  round_id INTEGER,
  is_lead INTEGER NOT NULL DEFAULT 0,
  announced_at TEXT,
  source_signal_id INTEGER,
  UNIQUE(investor_id, company_id, round_id)
);

CREATE TABLE IF NOT EXISTS enrichment_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL,
  field TEXT NOT NULL,
  value_json TEXT,               -- null value + reason when unavailable
  unavailable_reason TEXT,       -- e.g. 'requires Coresignal'
  fetched_at TEXT NOT NULL,
  ttl_hours INTEGER NOT NULL DEFAULT 168,
  source TEXT NOT NULL,
  confidence REAL,
  UNIQUE(company_id, field)
);

CREATE TABLE IF NOT EXISTS scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL,
  composite REAL,
  percentile REAL,               -- within (sector, stage) cohort — the primary output
  cohort_key TEXT,
  cohort_size INTEGER,
  cohort_low_confidence INTEGER NOT NULL DEFAULT 0,
  features_json TEXT NOT NULL,   -- full feature vector incl. nulls + reasons
  recommendation TEXT,           -- Pass | Watch | Deep Dive
  human_override TEXT,           -- partner-edited recommendation, always wins
  model_version TEXT,
  prompt_version TEXT,
  scored_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scores_company ON scores(company_id);

CREATE TABLE IF NOT EXISTS commentary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER,
  platform TEXT NOT NULL,
  author TEXT,
  author_credibility TEXT,
  sentiment TEXT,                -- positive | negative | mixed | neutral | [STUB]
  themes_json TEXT,
  quote TEXT,
  url TEXT,
  observed_at TEXT
);

CREATE TABLE IF NOT EXISTS briefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL,
  content_md TEXT NOT NULL,
  recommendation TEXT,
  generated_at TEXT NOT NULL,
  trigger TEXT NOT NULL,         -- on_demand | auto_threshold
  validated INTEGER NOT NULL DEFAULT 0,
  validation_notes TEXT
);

CREATE TABLE IF NOT EXISTS sectors_emerging (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  cluster_id INTEGER,
  signal_velocity REAL,
  consensus_volume REAL,
  ratio REAL,
  source_diversity INTEGER,
  evidence_json TEXT,            -- doc ids + urls
  thesis_md TEXT,
  detected_at TEXT NOT NULL,
  is_contrarian INTEGER NOT NULL DEFAULT 0,
  companies_json TEXT,           -- best companies sourced INSIDE this cluster (§2b)
  talent_flow INTEGER NOT NULL DEFAULT 0,  -- founder-move / frontier-lab docs in cluster
  terms_json TEXT                -- the cluster's defining terms, for auditability
);

CREATE TABLE IF NOT EXISTS news_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT,
  source TEXT,
  published_at TEXT,
  why_it_matters TEXT,
  relevance_score REAL,
  signal_id INTEGER
);

CREATE TABLE IF NOT EXISTS peer_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investor_id INTEGER NOT NULL,
  company_id INTEGER,
  event_type TEXT NOT NULL,      -- investment | fund_formation
  is_thesis_shift INTEGER NOT NULL DEFAULT 0,
  deviation_score REAL,
  observed_at TEXT,
  source_signal_id INTEGER
);

CREATE TABLE IF NOT EXISTS partner_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL,
  partner TEXT,
  action TEXT NOT NULL,          -- pass | watch | deep_dive | override | keep | remove
  score_at_time REAL,
  features_at_time_json TEXT,
  note TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS review_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL,            -- merge | stale | brief_validation | llm_parse_failure
  payload_json TEXT NOT NULL,
  confidence REAL,
  status TEXT NOT NULL DEFAULT 'open',  -- open | resolved
  resolved_by TEXT,
  resolved_at TEXT,
  created_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS digests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sent_at TEXT NOT NULL,
  kind TEXT NOT NULL,            -- mwf_digest | instant_alert
  contents_json TEXT NOT NULL,
  item_count INTEGER NOT NULL,
  delivered INTEGER NOT NULL DEFAULT 0,      -- was it actually emailed?
  delivery_detail TEXT                       -- provider id, or why not
);

-- Operational tables (build additions; noted in BUILD_LOG.md)

CREATE TABLE IF NOT EXISTS checkpoints (
  source_name TEXT PRIMARY KEY,
  checkpoint TEXT NOT NULL,      -- ISO date/time high-water mark; only advances on success
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS llm_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage TEXT NOT NULL,           -- classify | score | brief | digest | chat | sector_label
  model TEXT NOT NULL,
  prompt_tokens INTEGER NOT NULL DEFAULT 0,
  completion_tokens INTEGER NOT NULL DEFAULT 0,
  stubbed INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS alerts_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule TEXT NOT NULL,            -- tier1_coinvest | thesis_shift | watched_founder
  company_id INTEGER,
  dedupe_key TEXT UNIQUE,
  payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  delivered INTEGER NOT NULL DEFAULT 0,      -- was it actually emailed?
  delivery_detail TEXT                       -- provider id, or why not
);

-- Search runs: every search is a first-class record with live step progress
-- and a frozen snapshot of what it showed — so "what did Tuesday's search
-- find?" stays answerable forever, independent of later re-ranking.

CREATE TABLE IF NOT EXISTS runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL,             -- full | quick
  trigger_by TEXT NOT NULL,       -- manual | scheduled | boot
  status TEXT NOT NULL DEFAULT 'running',  -- running | done | failed
  started_at TEXT NOT NULL,
  finished_at TEXT,
  seconds REAL,
  stats_json TEXT,                -- funnel counts, new companies, etc.
  error TEXT
);

CREATE TABLE IF NOT EXISTS run_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL,
  seq INTEGER NOT NULL,
  key TEXT NOT NULL,              -- e.g. collect:edgar_formd, judge, briefs
  label TEXT NOT NULL,            -- plain-English, shown in the dashboard
  status TEXT NOT NULL DEFAULT 'pending',  -- pending | running | done | failed | skipped
  started_at TEXT,
  finished_at TEXT,
  seconds REAL,
  items INTEGER,                  -- e.g. signals fetched, companies judged
  detail TEXT
);
CREATE INDEX IF NOT EXISTS idx_run_steps_run ON run_steps(run_id);

CREATE TABLE IF NOT EXISTS run_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL,
  company_id INTEGER,
  name TEXT NOT NULL,
  sector TEXT,
  stage TEXT,
  recommendation TEXT,            -- as shown by THIS search (frozen)
  percentile REAL,
  cohort_size INTEGER,
  rank_in_cohort INTEGER,
  is_new INTEGER NOT NULL DEFAULT 0,   -- first time this company ever appeared
  captured_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_run_results_run ON run_results(run_id);

CREATE TABLE IF NOT EXISTS sheet_sync (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spreadsheet_id TEXT,
  spreadsheet_url TEXT,
  tabs_written INTEGER,
  edits_pulled INTEGER,
  status TEXT NOT NULL,          -- ok | not_configured | error
  detail TEXT,
  synced_at TEXT NOT NULL
);
